---
- hosts: all
  vars_prompt:
    - name: "install_dir"
      prompt: "Install directory"
      private: false
      default: "/opt/OctoPrint"
    - name: "new_hostname"
      prompt: "Hostname"
      private: false
      default: "octoprint.local"
    - name: "port"
      prompt: "OctoPrint listening Port"
      private: false
      default: 5000
    - name: "webcam_port"
      prompt: "Webcam listening Port"
      private: false
      default: 8080
    - name: "enable_haproxy"
      prompt: "Enable remote access on Port 80"
      private: false
      default: true
    - name: "enable_webcam"
      prompt: "Enable webcam"
      private: false
      default: true
    - name: "enable_touchui"
      prompt: "Enable touch ui"
      private: false
      default: true
  roles:
    - octoprint