---
- hosts: all
  vars_prompt:
    - name: "new_ip_address"
      prompt: "IP Address [Format: 192.168.1.1/24]"
      private: false
    - name: "gateway_address"
      prompt: "Gateway IP Address"
      private: false
      default: "192.168.1.1"
    - name: "iface"
      prompt: "Network Interface"
      private: false
      default: "eth0"
    - name: "dns_address"
      prompt: "DNS address(s)"
      private: false
      default: "192.168.1.1"
  roles:
    - { role: static_ip }